/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crypto;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author abhil
 */
public class EncryptFrame extends javax.swing.JFrame {

    /**
     * Creates new form EncryptFrame
     */
    public EncryptFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(240, 26, 47));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(58, 54, 60, 60);

        jButton2.setBackground(new java.awt.Color(43, 83, 74));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(136, 54, 60, 60);

        jButton3.setBackground(new java.awt.Color(234, 7, 240));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(214, 54, 60, 60);

        jButton4.setBackground(new java.awt.Color(96, 240, 77));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(292, 54, 60, 60);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(58, 132, 60, 60);

        jButton6.setBackground(new java.awt.Color(254, 93, 5));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(136, 132, 60, 60);

        jButton7.setBackground(new java.awt.Color(29, 168, 255));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(214, 132, 60, 60);

        jButton8.setBackground(new java.awt.Color(255, 119, 195));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(292, 132, 60, 60);

        jButton9.setBackground(new java.awt.Color(1, 111, 53));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(58, 210, 60, 60);

        jButton10.setBackground(new java.awt.Color(236, 251, 1));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(136, 210, 60, 60);

        jButton11.setBackground(new java.awt.Color(180, 129, 37));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(214, 210, 60, 60);

        jButton12.setBackground(new java.awt.Color(137, 3, 243));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(292, 210, 60, 60);

        jButton13.setBackground(new java.awt.Color(122, 150, 97));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(58, 288, 60, 60);

        jButton14.setBackground(new java.awt.Color(236, 130, 98));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(136, 288, 60, 60);

        jButton15.setBackground(new java.awt.Color(251, 83, 137));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(214, 288, 60, 60);

        jButton16.setBackground(new java.awt.Color(15, 245, 252));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(292, 288, 60, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhil\\Desktop\\anon1.jpg")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 410, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(346, 351, 411, 401);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("R");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(153, 34, 30, 58);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("G");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 34, 32, 58);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("B");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(463, 34, 28, 58);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(135, 110, 65, 50);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(jTextField2);
        jTextField2.setBounds(291, 110, 65, 50);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(jTextField3);
        jTextField3.setBounds(443, 110, 65, 50);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(jTextField4);
        jTextField4.setBounds(135, 205, 65, 50);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(jTextField5);
        jTextField5.setBounds(291, 205, 65, 50);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(jTextField6);
        jTextField6.setBounds(443, 205, 65, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("KEY");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(29, 220, 41, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Operations");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(29, 299, 115, 29);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton1.setText("+");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(230, 295, 45, 37);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton2.setText("-");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(356, 295, 37, 37);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Optimized Key");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(29, 375, 152, 29);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(jTextField7);
        jTextField7.setBounds(221, 360, 65, 55);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(jTextField8);
        jTextField8.setBounds(344, 360, 65, 55);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel2.add(jTextField9);
        jTextField9.setBounds(465, 360, 65, 55);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Select File");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(29, 457, 107, 29);

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jTextField10);
        jTextField10.setBounds(154, 454, 327, 35);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton17.setText("SELECT");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17);
        jButton17.setBounds(488, 453, 111, 37);

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton18.setText("ENCRYP");
        jPanel2.add(jButton18);
        jButton18.setBounds(130, 550, 150, 37);

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton19.setText("CLEAR");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton19);
        jButton19.setBounds(360, 550, 130, 37);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhil\\Desktop\\anon2.jpg")); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(-350, 0, 970, 680);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(858, 225, 600, 612);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhil\\Desktop\\anonymous1.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1960, 1060);

        jMenu1.setText("Manage Profile");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Update Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Encode Data");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Encrypt File");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Decode Data");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("Decrypt File");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Logout");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        SignUpUpdateFrame signupdate = new SignUpUpdateFrame();
        signupdate.setVisible(true);
        signupdate.setSize(1920,1080);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        EncryptFrame en = new EncryptFrame();
        en.setVisible(true);
        en.setSize(1920,1080);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
        DecryptFrame dc = new DecryptFrame();
        dc.setVisible(true);
        dc.setSize(1920,1080);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        mf.setSize(1920, 1080);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Color color = jButton1.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        
        
        jRadioButton2.setSelected(true);
        jRadioButton1.setSelected(false);
        String box1 = jTextField1.getText();
        String box2 = jTextField2.getText();
        String box3 = jTextField3.getText();
        String box4 = jTextField4.getText();
        String box5 = jTextField6.getText();
        String box6 = jTextField6.getText();
        
        int sub1 = 0, sub2 = 0, sub3 = 0;
        
        if(box1.isEmpty() || box2.isEmpty() || box3.isEmpty())
        {    
            JOptionPane.showMessageDialog(null, "Please choose colors to genarate Optimized key");
            jTextField7.setText(null);
            jTextField8.setText(null);
            jTextField9.setText(null);
        }
        
        else if(box4.isEmpty() || box5.isEmpty() || box6.isEmpty())
        {    
            JOptionPane.showMessageDialog(null, "Please enter key to genrate Optimized key");
            jTextField7.setText(null);
            jTextField8.setText(null);
            jTextField9.setText(null);
        }
        else
        {
            int b1 = Integer.parseInt(box1);
            int b2 = Integer.parseInt(box2);
            int b3 = Integer.parseInt(box3);
            int b4 = Integer.parseInt(box4);
            int b5 = Integer.parseInt(box5);
            int b6 = Integer.parseInt(box6);
        
            sub1 = b1 - b4;
            sub2 = b2 - b5;
            sub3 = b3 - b6;
            String s1 = Integer.toString(sub1);
            String s2 = Integer.toString(sub2);
            String s3 = Integer.toString(sub3);
        
            jTextField7.setText(s1);
            jTextField8.setText(s2);
            jTextField9.setText(s3);
        
        
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Color color = jButton2.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Color color = jButton3.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Color color = jButton4.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Color color = jButton5.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Color color = jButton6.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Color color = jButton7.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Color color = jButton8.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Color color = jButton9.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Color color = jButton10.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Color color = jButton11.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Color color = jButton12.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Color color = jButton13.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Color color = jButton14.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Color color = jButton15.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Color color = jButton16.getBackground();
        jTextField1.setText(Integer.toString(color.getRed()));
        jTextField2.setText(Integer.toString(color.getGreen()));
        jTextField3.setText(Integer.toString(color.getBlue()));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        
        
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        String box1 = jTextField1.getText();
        String box2 = jTextField2.getText();
        String box3 = jTextField3.getText();
        String box4 = jTextField4.getText();
        String box5 = jTextField6.getText();
        String box6 = jTextField6.getText();
        
        
        int sum1 = 0, sum2 = 0, sum3 = 0;
        if(box1.isEmpty() || box2.isEmpty() || box3.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please choose colors to genarate Optimized key");
            jTextField7.setText(null);
            jTextField8.setText(null);
            jTextField9.setText(null);
        }
        else if(box4.isEmpty() || box5.isEmpty() || box6.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter key to genrate Optimized key");
            jTextField7.setText(null);
            jTextField8.setText(null);
            jTextField9.setText(null);
        }
        else
        {
            int b1 = Integer.parseInt(box1);
            int b2 = Integer.parseInt(box2);
            int b3 = Integer.parseInt(box3);
            int b4 = Integer.parseInt(box4);
            int b5 = Integer.parseInt(box5);
            int b6 = Integer.parseInt(box6);
            sum1 = b1 + b4;
            sum2 = b2 + b5;
            sum3 = b3 + b6;
            
            String s1 = Integer.toString(sum1);
            String s2 = Integer.toString(sum2);
            String s3 = Integer.toString(sum3);
        
            jTextField7.setText(s1);
            jTextField8.setText(s2);
            jTextField9.setText(s3);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        JFileChooser fc=new JFileChooser();
        fc.showOpenDialog(fc);
        File sel=fc.getSelectedFile();
        String path=sel.getPath();
        jTextField10.setText(path);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncryptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncryptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncryptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncryptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncryptFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
